# https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/getting-started/
# https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/configuration/

camunda:
  client:
    mode: selfmanaged
    zeebe:
      enabled: true
      grpc-address: http://localhost:26500
      preferRestOverGrpc: false
      execution-threads: 100
      defaults:
        max-jobs-active: 40


waitforresult:
  creator:
    enabled: true
    processId: WaitForResultLoadTest
    numberOfLoops: 6000
    numberOfThreads: 40

  worker:
    enabled: true

logging:
  level:
    root: INFO