# https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/getting-started/
# https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/configuration/

camunda:
  client:
    mode: selfmanaged
    zeebe:
      enabled: true
      grpc-address: http://localhost:26500
      preferRestOverGrpc: false
      execution-threads: 100
      defaults:
        max-jobs-active: 100


waitforresult:
  resultworker:
    implementation: HOST
  creator:
    enabled: true
    processId: WaitForResultLoadTest
    numberOfLoops: 6000
    numberOfThreads: 5
    topicPrefix: end-creation-
    timeoutCreationInMs: 50000

  message:
    # Enable the message only if you enabled the creator: source of data is produce by the creator
    enabled: true
    name: blue
    topicPrefix: end-msg-


  worker:
    enabled: true



logging:
  level:
    root: INFO